### ISSUE TITLE
Is it possible to get card holder name and can support other type of cards like union pay and American Express?

### ISSUE THREAD

**Issue by vajjasivateja** [viliyantrbr/NFC-EMV-Payer#1]
In my project its necessary to get Card holder's name , if its possible pls give me suggestions to get that.
And also can we read Union pay and American Express cards also?

**Comment by n37sn4k3** [comment]
Yes, it is possible to get the cardholder name and I'm currently getting it (in my app if you select paycard you will be able to see the name if there is). I said if there is because some paycards do not contain a cardholder name, it is only written on the plastic. You can see how to get the name in the "ReadThread" (https://github.com/viliyantrbr/NFC-EMV-Payer/blob/master/app/src/main/java/com/viliyantrbr/nfcemvpayer/thread/ReadPaycardThread.java), currently lines 652-674 & 853-875. The TLV tag is 5F20. Do not forget to convert the "bytes" result to ASCII.

I have not tested if the app will read an AMEX or Union pay cards. If you want you can test it by adding their AIDs. Please tell me if you succeed with reading :). Thank you.

**Comment by vajjasivateja** [comment]
Hi thanks for your reply, I tried to test your app with Samsung galaxy 8 with Visa, but i haven't got CardHolder name though there is cardholder name on card. 

I have gone through LogUtil.d files only to find the details as card type, card number, expiry date but not cardholder name. Its not even showing the value as null. the log.d image is added below

can you update the code to show cardholder name in cards list fragment? I tried to add but because of some issue its not happening.
![screen shot 2018-07-19 at 4 35 13 pm](https://user-images.githubusercontent.com/28665548/43052724-e02f5888-8e5a-11e8-94e5-65ca7d21eb2c.png)


Is there anyway to test this code for getting holder name?

If possible can you make an aar library or maven or github for using this feature instantly to integrate into another app like https://github.com/devnied/EMV-NFC-Paycard-Enrollment library.

Thanks
